#region Copyright & OSS License
// Copyright Information
// All source is copyright, Kevin Wittmer
// See License.txt for more information (check Visual Studio Solution Items)
// ==================================
#endregion

using Baseball.ApiSharp.Dal.EfStructures;
using Baseball.ApiSharp.Data.Lahman;
using System.Linq;

namespace Baseball.ApiSharp.Dal.Initialization.SampleData
{
    public class ___GreatWhiteSoxPlayerData
    {
        public static void SeedData(LahmansDbContext dbContext)
        {
            BulkMasterPlayerInsert(dbContext);
            BulkPitchingPlayerInsert(dbContext);
            BulkBattingPlayerInsert(dbContext);
            BulkFieldingPlayerInsert(dbContext);
        }

        public static void BulkMasterPlayerInsert(LahmansDbContext dbContext)
        {
            if (dbContext.People.Count(m => m.PlayerId == "thomafr04") == 0)
            {
                dbContext.People.Add(new People()
                {
                    PlayerId = "thomafr04",
                    Bats = "R",
                    Throws = "R",
                    NameFirst = "Frank",
                    NameLast = "Thomas",
                    BbrefId = "thomafr04",
                    BirthCity = "Columbus",
                    BirthDay = 27,
                    BirthCountry = "USA",
                    BirthState = "GA",
                    BirthMonth = 5,
                    BirthYear = 1968,
                    Debut = "1990-08-02",
                    FinalGame = "2008-08-29",
                    Height = 77,
                    Weight = 240,
                    RetroId = "thomf001"
                });
            }

            dbContext.SaveChanges();
        }

        public static void BulkPitchingPlayerInsert(LahmansDbContext dbContext)
        {
            dbContext.SaveChanges();
        }

        public static void BulkBattingPlayerInsert(LahmansDbContext dbContext)
        {
            dbContext.Batting.Add(new Batting()
            {
                PlayerId = "thomafr04",
                YearId = 1990,
                Stint = 1,
                TeamId = "CHA",
                LgId = "AL",
                G = 60,
                Ab = 191,
                R = 39,
                _2b = 11,
                _3b = 3,
                H = 63,
                Hr = 7,
                Rbi = 31,
                Sb = 0,
                Cs = 1,
                Bb = 44,
                So = 54,
                Ibb = 0,
                Hbp = 2,
                Sh = 0,
                Sf = 3,
                Gidp = 5,
            });
            dbContext.Batting.Add(new Batting()
            {
                PlayerId = "thomafr04",
                YearId = 1991,
                Stint = 1,
                TeamId = "CHA",
                LgId = "AL",
                G = 158,
                Ab = 559,
                R = 104,
                _2b = 31,
                _3b = 2,
                H = 178,
                Hr = 32,
                Rbi = 109,
                Sb = 1,
                Cs = 2,
                Bb = 138,
                So = 112,
                Ibb = 13,
                Hbp = 1,
                Sh = 0,
                Sf = 2,
                Gidp = 20,
            });
            dbContext.Batting.Add(new Batting()
            {
                PlayerId = "thomafr04",
                YearId = 1992,
                Stint = 1,
                TeamId = "CHA",
                LgId = "AL",
                G = 160,
                Ab = 573,
                R = 108,
                _2b = 46,
                _3b = 2,
                H = 185,
                Hr = 24,
                Rbi = 115,
                Sb = 6,
                Cs = 3,
                Bb = 122,
                So = 88,
                Ibb = 6,
                Hbp = 5,
                Sh = 0,
                Sf = 11,
                Gidp = 19,
            });
            dbContext.Batting.Add(new Batting()
            {
                PlayerId = "thomafr04",
                YearId = 1993,
                Stint = 1,
                TeamId = "CHA",
                LgId = "AL",
                G = 153,
                Ab = 549,
                R = 106,
                _2b = 36,
                _3b = 0,
                H = 174,
                Hr = 41,
                Rbi = 128,
                Sb = 4,
                Cs = 2,
                Bb = 112,
                So = 54,
                Ibb = 23,
                Hbp = 2,
                Sh = 0,
                Sf = 13,
                Gidp = 10,
            });
            dbContext.Batting.Add(new Batting()
            {
                PlayerId = "thomafr04",
                YearId = 1994,
                Stint = 1,
                TeamId = "CHA",
                LgId = "AL",
                G = 113,
                Ab = 399,
                R = 106,
                _2b = 34,
                _3b = 1,
                H = 141,
                Hr = 38,
                Rbi = 101,
                Sb = 2,
                Cs = 3,
                Bb = 109,
                So = 61,
                Ibb = 12,
                Hbp = 2,
                Sh = 0,
                Sf = 7,
                Gidp = 15,
            });
            dbContext.Batting.Add(new Batting()
            {
                PlayerId = "thomafr04",
                YearId = 1995,
                Stint = 1,
                TeamId = "CHA",
                LgId = "AL",
                G = 145,
                Ab = 493,
                R = 102,
                _2b = 27,
                _3b = 0,
                H = 152,
                Hr = 40,
                Rbi = 111,
                Sb = 3,
                Cs = 2,
                Bb = 136,
                So = 74,
                Ibb = 29,
                Hbp = 6,
                Sh = 0,
                Sf = 12,
                Gidp = 14,
            });
            dbContext.Batting.Add(new Batting()
            {
                PlayerId = "thomafr04",
                YearId = 1996,
                Stint = 1,
                TeamId = "CHA",
                LgId = "AL",
                G = 141,
                Ab = 527,
                R = 110,
                _2b = 26,
                _3b = 0,
                H = 184,
                Hr = 40,
                Rbi = 134,
                Sb = 1,
                Cs = 1,
                Bb = 109,
                So = 70,
                Ibb = 26,
                Hbp = 5,
                Sh = 0,
                Sf = 8,
                Gidp = 25,
            });
            dbContext.Batting.Add(new Batting()
            {
                PlayerId = "thomafr04",
                YearId = 1997,
                Stint = 1,
                TeamId = "CHA",
                LgId = "AL",
                G = 146,
                Ab = 530,
                R = 110,
                _2b = 35,
                _3b = 0,
                H = 184,
                Hr = 35,
                Rbi = 125,
                Sb = 1,
                Cs = 1,
                Bb = 109,
                So = 69,
                Ibb = 9,
                Hbp = 3,
                Sh = 0,
                Sf = 7,
                Gidp = 15,
            });
            dbContext.Batting.Add(new Batting()
            {
                PlayerId = "thomafr04",
                YearId = 1998,
                Stint = 1,
                TeamId = "CHA",
                LgId = "AL",
                G = 160,
                Ab = 585,
                R = 109,
                _2b = 35,
                _3b = 2,
                H = 155,
                Hr = 29,
                Rbi = 109,
                Sb = 7,
                Cs = 0,
                Bb = 110,
                So = 93,
                Ibb = 2,
                Hbp = 6,
                Sh = 0,
                Sf = 11,
                Gidp = 14,
            });
            dbContext.Batting.Add(new Batting()
            {
                PlayerId = "thomafr04",
                YearId = 1999,
                Stint = 1,
                TeamId = "CHA",
                LgId = "AL",
                G = 135,
                Ab = 486,
                R = 74,
                _2b = 36,
                _3b = 0,
                H = 148,
                Hr = 15,
                Rbi = 77,
                Sb = 3,
                Cs = 3,
                Bb = 87,
                So = 66,
                Ibb = 13,
                Hbp = 9,
                Sh = 0,
                Sf = 8,
                Gidp = 14,
            });
            dbContext.Batting.Add(new Batting()
            {
                PlayerId = "thomafr04",
                YearId = 2000,
                Stint = 1,
                TeamId = "CHA",
                LgId = "AL",
                G = 159,
                Ab = 582,
                R = 115,
                _2b = 44,
                _3b = 0,
                H = 191,
                Hr = 43,
                Rbi = 143,
                Sb = 1,
                Cs = 3,
                Bb = 112,
                So = 94,
                Ibb = 18,
                Hbp = 5,
                Sh = 0,
                Sf = 8,
                Gidp = 13,
            });
            dbContext.Batting.Add(new Batting()
            {
                PlayerId = "thomafr04",
                YearId = 2001,
                Stint = 1,
                TeamId = "CHA",
                LgId = "AL",
                G = 20,
                Ab = 68,
                R = 8,
                _2b = 3,
                _3b = 0,
                H = 15,
                Hr = 4,
                Rbi = 10,
                Sb = 0,
                Cs = 0,
                Bb = 10,
                So = 12,
                Ibb = 2,
                Hbp = 0,
                Sh = 0,
                Sf = 1,
                Gidp = 0,
            });
            dbContext.Batting.Add(new Batting()
            {
                PlayerId = "thomafr04",
                YearId = 2002,
                Stint = 1,
                TeamId = "CHA",
                LgId = "AL",
                G = 148,
                Ab = 523,
                R = 77,
                _2b = 29,
                _3b = 1,
                H = 132,
                Hr = 28,
                Rbi = 92,
                Sb = 3,
                Cs = 0,
                Bb = 88,
                So = 115,
                Ibb = 2,
                Hbp = 7,
                Sh = 0,
                Sf = 10,
                Gidp = 10,
            });
            dbContext.Batting.Add(new Batting()
            {
                PlayerId = "thomafr04",
                YearId = 2003,
                Stint = 1,
                TeamId = "CHA",
                LgId = "AL",
                G = 153,
                Ab = 546,
                R = 87,
                _2b = 35,
                _3b = 0,
                H = 146,
                Hr = 42,
                Rbi = 105,
                Sb = 0,
                Cs = 0,
                Bb = 100,
                So = 115,
                Ibb = 4,
                Hbp = 12,
                Sh = 0,
                Sf = 4,
                Gidp = 11,
            });
            dbContext.Batting.Add(new Batting()
            {
                PlayerId = "thomafr04",
                YearId = 2004,
                Stint = 1,
                TeamId = "CHA",
                LgId = "AL",
                G = 74,
                Ab = 240,
                R = 53,
                _2b = 16,
                _3b = 0,
                H = 65,
                Hr = 18,
                Rbi = 49,
                Sb = 0,
                Cs = 2,
                Bb = 64,
                So = 57,
                Ibb = 3,
                Hbp = 6,
                Sh = 0,
                Sf = 1,
                Gidp = 2,
            });

            /*
            // TODO: Check prior to insert or find another simpler way to manage
            dbContext.Batting.Add(new Batting()
            {
                PlayerId = "thomafr04",
                YearId = 2005,
                Stint = 1,
                TeamId = "CHA",
                LgId = "AL",
                G = 34,
                Ab = 105,
                R = 19,
                _2b = 3,
                _3b = 0,
                H = 23,
                Hr = 12,
                Rbi = 26,
                Sb = 0,
                Cs = 0,
                Bb = 16,
                So = 31,
                Ibb = 0,
                Hbp = 0,
                Sh = 0,
                Sf = 3,
                Gidp = 2,
            });
            */
            dbContext.Batting.Add(new Batting()
            {
                PlayerId = "thomafr04",
                YearId = 2006,
                Stint = 1,
                TeamId = "OAK",
                LgId = "AL",
                G = 137,
                Ab = 466,
                R = 77,
                _2b = 11,
                _3b = 0,
                H = 126,
                Hr = 39,
                Rbi = 114,
                Sb = 0,
                Cs = 0,
                Bb = 81,
                So = 81,
                Ibb = 3,
                Hbp = 6,
                Sh = 0,
                Sf = 6,
                Gidp = 13,
            });
            dbContext.Batting.Add(new Batting()
            {
                PlayerId = "thomafr04",
                YearId = 2007,
                Stint = 1,
                TeamId = "TOR",
                LgId = "AL",
                G = 155,
                Ab = 531,
                R = 63,
                _2b = 30,
                _3b = 0,
                H = 147,
                Hr = 26,
                Rbi = 95,
                Sb = 0,
                Cs = 0,
                Bb = 81,
                So = 94,
                Ibb = 3,
                Hbp = 7,
                Sh = 0,
                Sf = 5,
                Gidp = 14,
            });
            dbContext.Batting.Add(new Batting()
            {
                PlayerId = "thomafr04",
                YearId = 2008,
                Stint = 1,
                TeamId = "TOR",
                LgId = "AL",
                G = 16,
                Ab = 60,
                R = 7,
                _2b = 1,
                _3b = 0,
                H = 10,
                Hr = 3,
                Rbi = 11,
                Sb = 0,
                Cs = 0,
                Bb = 11,
                So = 13,
                Ibb = 0,
                Hbp = 1,
                Sh = 0,
                Sf = 0,
                Gidp = 3,
            });
            dbContext.Batting.Add(new Batting()
            {
                PlayerId = "thomafr04",
                YearId = 2008,
                Stint = 2,
                TeamId = "OAK",
                LgId = "AL",
                G = 55,
                Ab = 186,
                R = 20,
                _2b = 6,
                _3b = 1,
                H = 49,
                Hr = 5,
                Rbi = 19,
                Sb = 0,
                Cs = 0,
                Bb = 28,
                So = 44,
                Ibb = 0,
                Hbp = 2,
                Sh = 0,
                Sf = 1,
                Gidp = 6,
            });
            dbContext.SaveChanges();
        }

        public static void BulkFieldingPlayerInsert(LahmansDbContext dbContext)
        {
            dbContext.Fielding.Add(new Fielding()
            {
                PlayerId = "thomafr03",
                YearId = 1951,
                Stint = 1,
                TeamId = "PIT",
                LgId = "NL",
                Pos = "OF",
                G = 37,
                Po = 87,
                A = 5,
                E = 0,
                Dp = 2,
            });
            dbContext.Fielding.Add(new Fielding()
            {
                PlayerId = "thomafr03",
                YearId = 1952,
                Stint = 1,
                TeamId = "PIT",
                LgId = "NL",
                Pos = "OF",
                G = 5,
                Po = 8,
                A = 1,
                E = 0,
                Dp = 0,
            });
            dbContext.Fielding.Add(new Fielding()
            {
                PlayerId = "thomafr03",
                YearId = 1953,
                Stint = 1,
                TeamId = "PIT",
                LgId = "NL",
                Pos = "OF",
                G = 118,
                Po = 306,
                A = 17,
                E = 8,
                Dp = 1,
            });
            dbContext.Fielding.Add(new Fielding()
            {
                PlayerId = "thomafr03",
                YearId = 1954,
                Stint = 1,
                TeamId = "PIT",
                LgId = "NL",
                Pos = "OF",
                G = 153,
                Gs = 152,
                InnOuts = 3984,
                Po = 418,
                A = 14,
                E = 5,
                Dp = 2,
            });
            dbContext.Fielding.Add(new Fielding()
            {
                PlayerId = "thomafr03",
                YearId = 1955,
                Stint = 1,
                TeamId = "PIT",
                LgId = "NL",
                Pos = "OF",
                G = 139,
                Gs = 136,
                InnOuts = 3615,
                Po = 307,
                A = 8,
                E = 5,
                Dp = 3,
            });
            dbContext.Fielding.Add(new Fielding()
            {
                PlayerId = "thomafr03",
                YearId = 1956,
                Stint = 1,
                TeamId = "PIT",
                LgId = "NL",
                Pos = "2B",
                G = 4,
                Gs = 0,
                InnOuts = 17,
                Po = 3,
                A = 0,
                E = 0,
                Dp = 0,
            });
            dbContext.Fielding.Add(new Fielding()
            {
                PlayerId = "thomafr03",
                YearId = 1956,
                Stint = 1,
                TeamId = "PIT",
                LgId = "NL",
                Pos = "3B",
                G = 111,
                Gs = 105,
                InnOuts = 2710,
                Po = 118,
                A = 176,
                E = 18,
                Dp = 21,
            });
            dbContext.Fielding.Add(new Fielding()
            {
                PlayerId = "thomafr03",
                YearId = 1956,
                Stint = 1,
                TeamId = "PIT",
                LgId = "NL",
                Pos = "OF",
                G = 56,
                Gs = 50,
                InnOuts = 1255,
                Po = 95,
                A = 3,
                E = 0,
                Dp = 1,
            });
            dbContext.Fielding.Add(new Fielding()
            {
                PlayerId = "thomafr03",
                YearId = 1957,
                Stint = 1,
                TeamId = "PIT",
                LgId = "NL",
                Pos = "1B",
                G = 71,
                Gs = 70,
                InnOuts = 1857,
                Po = 597,
                A = 52,
                E = 15,
                Dp = 53,
            });
            dbContext.Fielding.Add(new Fielding()
            {
                PlayerId = "thomafr03",
                YearId = 1957,
                Stint = 1,
                TeamId = "PIT",
                LgId = "NL",
                Pos = "3B",
                G = 31,
                Gs = 24,
                InnOuts = 698,
                Po = 27,
                A = 53,
                E = 7,
                Dp = 4,
            });
            dbContext.Fielding.Add(new Fielding()
            {
                PlayerId = "thomafr03",
                YearId = 1957,
                Stint = 1,
                TeamId = "PIT",
                LgId = "NL",
                Pos = "OF",
                G = 59,
                Gs = 57,
                InnOuts = 1504,
                Po = 105,
                A = 14,
                E = 3,
                Dp = 3,
            });
            dbContext.Fielding.Add(new Fielding()
            {
                PlayerId = "thomafr03",
                YearId = 1958,
                Stint = 1,
                TeamId = "PIT",
                LgId = "NL",
                Pos = "1B",
                G = 2,
                Gs = 2,
                InnOuts = 54,
                Po = 20,
                A = 3,
                E = 0,
                Dp = 1,
            });
            dbContext.Fielding.Add(new Fielding()
            {
                PlayerId = "thomafr03",
                YearId = 1958,
                Stint = 1,
                TeamId = "PIT",
                LgId = "NL",
                Pos = "3B",
                G = 139,
                Gs = 139,
                InnOuts = 3668,
                Po = 122,
                A = 240,
                E = 29,
                Dp = 21,
            });
            dbContext.Fielding.Add(new Fielding()
            {
                PlayerId = "thomafr03",
                YearId = 1958,
                Stint = 1,
                TeamId = "PIT",
                LgId = "NL",
                Pos = "OF",
                G = 8,
                Gs = 7,
                InnOuts = 183,
                Po = 18,
                A = 0,
                E = 1,
                Dp = 0,
            });
            dbContext.Fielding.Add(new Fielding()
            {
                PlayerId = "thomafr03",
                YearId = 1959,
                Stint = 1,
                TeamId = "CIN",
                LgId = "NL",
                Pos = "1B",
                G = 14,
                Gs = 14,
                InnOuts = 354,
                Po = 111,
                A = 15,
                E = 2,
                Dp = 11,
            });
            dbContext.Fielding.Add(new Fielding()
            {
                PlayerId = "thomafr03",
                YearId = 1959,
                Stint = 1,
                TeamId = "CIN",
                LgId = "NL",
                Pos = "3B",
                G = 64,
                Gs = 63,
                InnOuts = 1536,
                Po = 55,
                A = 111,
                E = 13,
                Dp = 8,
            });
            dbContext.Fielding.Add(new Fielding()
            {
                PlayerId = "thomafr03",
                YearId = 1959,
                Stint = 1,
                TeamId = "CIN",
                LgId = "NL",
                Pos = "OF",
                G = 33,
                Gs = 18,
                InnOuts = 550,
                Po = 40,
                A = 0,
                E = 4,
                Dp = 0,
            });
            dbContext.Fielding.Add(new Fielding()
            {
                PlayerId = "thomafr03",
                YearId = 1960,
                Stint = 1,
                TeamId = "CHN",
                LgId = "NL",
                Pos = "1B",
                G = 50,
                Gs = 48,
                InnOuts = 1242,
                Po = 426,
                A = 34,
                E = 8,
                Dp = 36,
            });
            dbContext.Fielding.Add(new Fielding()
            {
                PlayerId = "thomafr03",
                YearId = 1960,
                Stint = 1,
                TeamId = "CHN",
                LgId = "NL",
                Pos = "3B",
                G = 33,
                Gs = 33,
                InnOuts = 783,
                Po = 25,
                A = 55,
                E = 6,
                Dp = 4,
            });
            dbContext.Fielding.Add(new Fielding()
            {
                PlayerId = "thomafr03",
                YearId = 1960,
                Stint = 1,
                TeamId = "CHN",
                LgId = "NL",
                Pos = "OF",
                G = 49,
                Gs = 39,
                InnOuts = 1097,
                Po = 77,
                A = 3,
                E = 3,
                Dp = 0,
            });
            dbContext.Fielding.Add(new Fielding()
            {
                PlayerId = "thomafr03",
                YearId = 1961,
                Stint = 1,
                TeamId = "CHN",
                LgId = "NL",
                Pos = "1B",
                G = 6,
                Gs = 4,
                InnOuts = 108,
                Po = 41,
                A = 2,
                E = 0,
                Dp = 2,
            });
            dbContext.Fielding.Add(new Fielding()
            {
                PlayerId = "thomafr03",
                YearId = 1961,
                Stint = 1,
                TeamId = "CHN",
                LgId = "NL",
                Pos = "OF",
                G = 10,
                Gs = 8,
                InnOuts = 225,
                Po = 9,
                A = 2,
                E = 0,
                Dp = 0,
            });
            dbContext.Fielding.Add(new Fielding()
            {
                PlayerId = "thomafr03",
                YearId = 1961,
                Stint = 2,
                TeamId = "ML1",
                LgId = "NL",
                Pos = "1B",
                G = 11,
                Gs = 4,
                InnOuts = 136,
                Po = 48,
                A = 4,
                E = 0,
                Dp = 6,
            });
            dbContext.Fielding.Add(new Fielding()
            {
                PlayerId = "thomafr03",
                YearId = 1961,
                Stint = 2,
                TeamId = "ML1",
                LgId = "NL",
                Pos = "OF",
                G = 109,
                Gs = 109,
                InnOuts = 2824,
                Po = 202,
                A = 4,
                E = 10,
                Dp = 0,
            });
            dbContext.Fielding.Add(new Fielding()
            {
                PlayerId = "thomafr03",
                YearId = 1962,
                Stint = 1,
                TeamId = "NYN",
                LgId = "NL",
                Pos = "1B",
                G = 11,
                Gs = 9,
                InnOuts = 235,
                Po = 88,
                A = 3,
                E = 1,
                Dp = 7,
            });
            dbContext.Fielding.Add(new Fielding()
            {
                PlayerId = "thomafr03",
                YearId = 1962,
                Stint = 1,
                TeamId = "NYN",
                LgId = "NL",
                Pos = "3B",
                G = 10,
                Gs = 10,
                InnOuts = 259,
                Po = 7,
                A = 19,
                E = 4,
                Dp = 1,
            });
            dbContext.Fielding.Add(new Fielding()
            {
                PlayerId = "thomafr03",
                YearId = 1962,
                Stint = 1,
                TeamId = "NYN",
                LgId = "NL",
                Pos = "OF",
                G = 126,
                Gs = 126,
                InnOuts = 3239,
                Po = 216,
                A = 14,
                E = 9,
                Dp = 0,
            });
            dbContext.Fielding.Add(new Fielding()
            {
                PlayerId = "thomafr03",
                YearId = 1963,
                Stint = 1,
                TeamId = "NYN",
                LgId = "NL",
                Pos = "1B",
                G = 15,
                Gs = 15,
                InnOuts = 362,
                Po = 146,
                A = 9,
                E = 1,
                Dp = 9,
            });
            dbContext.Fielding.Add(new Fielding()
            {
                PlayerId = "thomafr03",
                YearId = 1963,
                Stint = 1,
                TeamId = "NYN",
                LgId = "NL",
                Pos = "3B",
                G = 1,
                Gs = 0,
                InnOuts = 6,
                Po = 0,
                A = 0,
                E = 1,
                Dp = 0,
            });
            dbContext.Fielding.Add(new Fielding()
            {
                PlayerId = "thomafr03",
                YearId = 1963,
                Stint = 1,
                TeamId = "NYN",
                LgId = "NL",
                Pos = "OF",
                G = 96,
                Gs = 94,
                InnOuts = 2350,
                Po = 158,
                A = 8,
                E = 2,
                Dp = 1,
            });
            dbContext.Fielding.Add(new Fielding()
            {
                PlayerId = "thomafr03",
                YearId = 1964,
                Stint = 1,
                TeamId = "NYN",
                LgId = "NL",
                Pos = "1B",
                G = 19,
                Gs = 17,
                InnOuts = 420,
                Po = 142,
                A = 14,
                E = 1,
                Dp = 11,
            });
            dbContext.Fielding.Add(new Fielding()
            {
                PlayerId = "thomafr03",
                YearId = 1964,
                Stint = 1,
                TeamId = "NYN",
                LgId = "NL",
                Pos = "3B",
                G = 2,
                Gs = 0,
                InnOuts = 12,
                Po = 1,
                A = 2,
                E = 0,
                Dp = 0,
            });
            dbContext.Fielding.Add(new Fielding()
            {
                PlayerId = "thomafr03",
                YearId = 1964,
                Stint = 1,
                TeamId = "NYN",
                LgId = "NL",
                Pos = "OF",
                G = 31,
                Gs = 31,
                InnOuts = 809,
                Po = 58,
                A = 2,
                E = 0,
                Dp = 1,
            });
            dbContext.Fielding.Add(new Fielding()
            {
                PlayerId = "thomafr03",
                YearId = 1964,
                Stint = 2,
                TeamId = "PHI",
                LgId = "NL",
                Pos = "1B",
                G = 36,
                Gs = 36,
                InnOuts = 956,
                Po = 297,
                A = 28,
                E = 8,
                Dp = 37,
            });
            dbContext.Fielding.Add(new Fielding()
            {
                PlayerId = "thomafr03",
                YearId = 1965,
                Stint = 1,
                TeamId = "PHI",
                LgId = "NL",
                Pos = "1B",
                G = 11,
                Gs = 10,
                InnOuts = 244,
                Po = 88,
                A = 4,
                E = 1,
                Dp = 10,
            });
            dbContext.Fielding.Add(new Fielding()
            {
                PlayerId = "thomafr03",
                YearId = 1965,
                Stint = 1,
                TeamId = "PHI",
                LgId = "NL",
                Pos = "3B",
                G = 1,
                Gs = 0,
                InnOuts = 6,
                Po = 0,
                A = 1,
                E = 1,
                Dp = 0,
            });
            dbContext.Fielding.Add(new Fielding()
            {
                PlayerId = "thomafr03",
                YearId = 1965,
                Stint = 1,
                TeamId = "PHI",
                LgId = "NL",
                Pos = "OF",
                G = 12,
                Gs = 5,
                InnOuts = 153,
                Po = 10,
                A = 1,
                E = 0,
                Dp = 0,
            });
            dbContext.Fielding.Add(new Fielding()
            {
                PlayerId = "thomafr03",
                YearId = 1965,
                Stint = 2,
                TeamId = "HOU",
                LgId = "NL",
                Pos = "1B",
                G = 16,
                Gs = 12,
                InnOuts = 323,
                Po = 118,
                A = 6,
                E = 2,
                Dp = 11,
            });
            dbContext.Fielding.Add(new Fielding()
            {
                PlayerId = "thomafr03",
                YearId = 1965,
                Stint = 2,
                TeamId = "HOU",
                LgId = "NL",
                Pos = "3B",
                G = 2,
                Gs = 0,
                InnOuts = 9,
                Po = 0,
                A = 0,
                E = 0,
                Dp = 0,
            });
            dbContext.Fielding.Add(new Fielding()
            {
                PlayerId = "thomafr03",
                YearId = 1965,
                Stint = 2,
                TeamId = "HOU",
                LgId = "NL",
                Pos = "OF",
                G = 1,
                Gs = 1,
                InnOuts = 18,
                Po = 0,
                A = 0,
                E = 0,
                Dp = 0,
            });
            dbContext.Fielding.Add(new Fielding()
            {
                PlayerId = "thomafr03",
                YearId = 1965,
                Stint = 3,
                TeamId = "ML1",
                LgId = "NL",
                Pos = "1B",
                G = 6,
                Gs = 6,
                InnOuts = 150,
                Po = 44,
                A = 3,
                E = 1,
                Dp = 3,
            });
            dbContext.Fielding.Add(new Fielding()
            {
                PlayerId = "thomafr03",
                YearId = 1965,
                Stint = 3,
                TeamId = "ML1",
                LgId = "NL",
                Pos = "OF",
                G = 3,
                Gs = 2,
                InnOuts = 57,
                Po = 2,
                A = 0,
                E = 0,
                Dp = 0,
            });
            dbContext.Fielding.Add(new Fielding()
            {
                PlayerId = "thomafr04",
                YearId = 1990,
                Stint = 1,
                TeamId = "CHA",
                LgId = "AL",
                Pos = "1B",
                G = 51,
                Gs = 51,
                InnOuts = 1261,
                Po = 428,
                A = 26,
                E = 5,
                Dp = 53,
            });
            dbContext.Fielding.Add(new Fielding()
            {
                PlayerId = "thomafr04",
                YearId = 1991,
                Stint = 1,
                TeamId = "CHA",
                LgId = "AL",
                Pos = "1B",
                G = 56,
                Gs = 56,
                InnOuts = 1430,
                Po = 459,
                A = 27,
                E = 2,
                Dp = 43,
            });
            dbContext.Fielding.Add(new Fielding()
            {
                PlayerId = "thomafr04",
                YearId = 1992,
                Stint = 1,
                TeamId = "CHA",
                LgId = "AL",
                Pos = "1B",
                G = 158,
                Gs = 157,
                InnOuts = 4218,
                Po = 1428,
                A = 92,
                E = 13,
                Dp = 112,
            });
            dbContext.Fielding.Add(new Fielding()
            {
                PlayerId = "thomafr04",
                YearId = 1993,
                Stint = 1,
                TeamId = "CHA",
                LgId = "AL",
                Pos = "1B",
                G = 150,
                Gs = 149,
                InnOuts = 3902,
                Po = 1222,
                A = 83,
                E = 15,
                Dp = 128,
            });
            dbContext.Fielding.Add(new Fielding()
            {
                PlayerId = "thomafr04",
                YearId = 1994,
                Stint = 1,
                TeamId = "CHA",
                LgId = "AL",
                Pos = "1B",
                G = 99,
                Gs = 99,
                InnOuts = 2601,
                Po = 735,
                A = 45,
                E = 7,
                Dp = 74,
            });
            dbContext.Fielding.Add(new Fielding()
            {
                PlayerId = "thomafr04",
                YearId = 1995,
                Stint = 1,
                TeamId = "CHA",
                LgId = "AL",
                Pos = "1B",
                G = 90,
                Gs = 89,
                InnOuts = 2317,
                Po = 738,
                A = 34,
                E = 7,
                Dp = 67,
            });
            dbContext.Fielding.Add(new Fielding()
            {
                PlayerId = "thomafr04",
                YearId = 1996,
                Stint = 1,
                TeamId = "CHA",
                LgId = "AL",
                Pos = "1B",
                G = 139,
                Gs = 139,
                InnOuts = 3696,
                Po = 1098,
                A = 85,
                E = 9,
                Dp = 111,
            });
            dbContext.Fielding.Add(new Fielding()
            {
                PlayerId = "thomafr04",
                YearId = 1997,
                Stint = 1,
                TeamId = "CHA",
                LgId = "AL",
                Pos = "1B",
                G = 97,
                Gs = 97,
                InnOuts = 2468,
                Po = 739,
                A = 49,
                E = 11,
                Dp = 70,
            });
            dbContext.Fielding.Add(new Fielding()
            {
                PlayerId = "thomafr04",
                YearId = 1998,
                Stint = 1,
                TeamId = "CHA",
                LgId = "AL",
                Pos = "1B",
                G = 14,
                Gs = 14,
                InnOuts = 342,
                Po = 116,
                A = 6,
                E = 2,
                Dp = 12,
            });
            dbContext.Fielding.Add(new Fielding()
            {
                PlayerId = "thomafr04",
                YearId = 1999,
                Stint = 1,
                TeamId = "CHA",
                LgId = "AL",
                Pos = "1B",
                G = 49,
                Gs = 50,
                InnOuts = 1264,
                Po = 385,
                A = 18,
                E = 4,
                Dp = 40,
            });
            dbContext.Fielding.Add(new Fielding()
            {
                PlayerId = "thomafr04",
                YearId = 2000,
                Stint = 1,
                TeamId = "CHA",
                LgId = "AL",
                Pos = "1B",
                G = 30,
                Gs = 30,
                InnOuts = 775,
                Po = 267,
                A = 15,
                E = 1,
                Dp = 38,
            });
            dbContext.Fielding.Add(new Fielding()
            {
                PlayerId = "thomafr04",
                YearId = 2001,
                Stint = 1,
                TeamId = "CHA",
                LgId = "AL",
                Pos = "1B",
                G = 3,
                Gs = 3,
                InnOuts = 59,
                Po = 20,
                A = 1,
                E = 1,
                Dp = 2,
            });
            dbContext.Fielding.Add(new Fielding()
            {
                PlayerId = "thomafr04",
                YearId = 2002,
                Stint = 1,
                TeamId = "CHA",
                LgId = "AL",
                Pos = "1B",
                G = 4,
                Gs = 4,
                InnOuts = 93,
                Po = 38,
                A = 4,
                E = 2,
                Dp = 5,
            });
            dbContext.Fielding.Add(new Fielding()
            {
                PlayerId = "thomafr04",
                YearId = 2003,
                Stint = 1,
                TeamId = "CHA",
                LgId = "AL",
                Pos = "1B",
                G = 27,
                Gs = 27,
                InnOuts = 627,
                Po = 206,
                A = 9,
                E = 1,
                Dp = 19,
            });
            dbContext.Fielding.Add(new Fielding()
            {
                PlayerId = "thomafr04",
                YearId = 2004,
                Stint = 1,
                TeamId = "CHA",
                LgId = "AL",
                Pos = "1B",
                G = 4,
                Gs = 4,
                InnOuts = 97,
                Po = 31,
                A = 3,
                E = 0,
                Dp = 2,
            });
            dbContext.SaveChanges();
        }
    }
}
